export type ScenarioTicker = {
  ticker: string;
  name: string;
  reason: string;
};

export type MacroScenario = {
  id: string;
  emoji: string;
  title: string;
  thesis: string;
  tags: string[];
  keywords: string[]; // lowercase, matched against headline substrings
  long: ScenarioTicker[];
  avoid: ScenarioTicker[];
  timeHorizon: "days" | "weeks" | "months" | "years";
  category: "energy" | "monetary" | "geopolitical" | "tech" | "economy" | "policy" | "markets";
};

export const MACRO_SCENARIOS: MacroScenario[] = [
  // ─── ENERGY ────────────────────────────────────────────────────────────────
  {
    id: "hormuz-reopens",
    emoji: "🛳️",
    title: "Strait of Hormuz Reopens",
    thesis: "If US-Iran tensions ease and shipping lanes normalize, fuel costs drop sharply and global risk appetite returns. Airlines and cruise lines — whose margins are crushed by fuel costs — get the biggest immediate lift. Refiners that built in a geopolitical premium give some back.",
    tags: ["Geopolitical", "Energy"],
    keywords: ["hormuz", "iran sanctions", "iran nuclear deal", "iran deal", "persian gulf", "iran trade", "sanctions relief"],
    long: [
      { ticker: "AAL", name: "American Airlines", reason: "Jet fuel is 25–30% of operating costs — direct margin expansion" },
      { ticker: "DAL", name: "Delta Air Lines", reason: "Largest US carrier by revenue; fuel cost relief flows straight to earnings" },
      { ticker: "CCL", name: "Carnival Corp", reason: "Cruise lines burn bunker fuel — reopened lanes cut cost and restore EM itineraries" },
      { ticker: "RCL", name: "Royal Caribbean", reason: "Premium cruise, heavy fuel exposure, also gains from normalized EM demand" },
      { ticker: "JBLU", name: "JetBlue", reason: "Lower-margin carrier, fuel savings are proportionally largest" },
      { ticker: "UPS", name: "UPS", reason: "Global logistics — fuel surcharges to shippers shrink, volume picks up" },
    ],
    avoid: [
      { ticker: "XOM", name: "Exxon Mobil", reason: "Loses geopolitical oil price premium" },
      { ticker: "CVX", name: "Chevron", reason: "Same dynamic — crude supply concern eases" },
    ],
    timeHorizon: "weeks",
    category: "geopolitical",
  },
  {
    id: "oil-supply-shock",
    emoji: "🛢️",
    title: "Oil Supply Shock",
    thesis: "OPEC+ deep cuts or a major supply disruption send crude sharply higher. Integrated majors, E&P companies, and refiners all benefit from higher commodity prices. Losers are any businesses where energy is a significant input cost.",
    tags: ["Energy", "Commodities"],
    keywords: ["opec cut", "opec+ cut", "oil production cut", "crude supply", "oil output cut", "oil shortage", "supply cut", "barrel cut"],
    long: [
      { ticker: "XOM", name: "Exxon Mobil", reason: "Largest US integrated major — upstream profits soar with crude prices" },
      { ticker: "CVX", name: "Chevron", reason: "Strong upstream-to-downstream mix benefits both directions of the move" },
      { ticker: "OXY", name: "Occidental Petroleum", reason: "Pure-play US E&P with high operational leverage to crude price" },
      { ticker: "EOG", name: "EOG Resources", reason: "Low-cost shale producer — margins expand significantly at $90+ oil" },
      { ticker: "VLO", name: "Valero Energy", reason: "Refining crack spreads historically widen in supply shocks" },
      { ticker: "HAL", name: "Halliburton", reason: "Oilfield services boom as producers accelerate drilling" },
    ],
    avoid: [
      { ticker: "AAL", name: "American Airlines", reason: "Jet fuel spike hits margins immediately" },
      { ticker: "DAL", name: "Delta Air Lines", reason: "Same fuel cost pressure" },
      { ticker: "FDX", name: "FedEx", reason: "Fuel surcharges lag cost increases; logistics margins compress" },
    ],
    timeHorizon: "weeks",
    category: "energy",
  },
  {
    id: "nuclear-revival",
    emoji: "⚛️",
    title: "Nuclear Energy Revival",
    thesis: "Data center power demand and net-zero commitments drive a renaissance in nuclear. Utilities with existing nuclear fleets get revalued, uranium miners are supply-constrained, and next-gen SMR developers attract serious capital. This is a multi-year trend that's already accelerating.",
    tags: ["Energy", "Tech Infrastructure"],
    keywords: ["nuclear power", "nuclear energy", "smr", "uranium demand", "nuclear plant", "data center power", "nuclear deal", "nuclear capacity", "nuclear reactor"],
    long: [
      { ticker: "CEG", name: "Constellation Energy", reason: "Largest US nuclear fleet operator — directly benefits from power price premium" },
      { ticker: "VST", name: "Vistra Energy", reason: "Nuclear + gas mix; signed landmark hyperscaler power deals" },
      { ticker: "CCJ", name: "Cameco", reason: "World's largest publicly traded uranium producer; supply is structurally tight" },
      { ticker: "NNE", name: "Nano Nuclear Energy", reason: "Micro-reactor developer — high-beta speculative play on SMR licensing" },
      { ticker: "BWX", name: "BWX Technologies", reason: "Manufactures naval nuclear reactors; also SMR components" },
      { ticker: "NRG", name: "NRG Energy", reason: "Power generator increasingly pivoting capacity to data center offtake deals" },
    ],
    avoid: [
      { ticker: "ENPH", name: "Enphase Energy", reason: "Competing baseload narrative shifts capex away from distributed solar" },
    ],
    timeHorizon: "years",
    category: "energy",
  },

  // ─── MONETARY POLICY ────────────────────────────────────────────────────────
  {
    id: "fed-rate-cut",
    emoji: "📉",
    title: "Fed Rate Cut Cycle Begins",
    thesis: "When the Fed starts cutting, borrowing costs fall and rate-sensitive assets re-rate sharply upward. Homebuilders get a double boost: lower mortgage rates drive buyer demand AND cheaper land financing. REITs re-rate as cap rate compression resumes. Small-cap growth stocks see their discount rates fall.",
    tags: ["Monetary Policy", "Real Estate"],
    keywords: ["rate cut", "fed cut", "dovish", "pivot", "lower rates", "rate reduction", "bps cut", "fomc cut", "interest rate cut", "fed funds cut", "monetary easing"],
    long: [
      { ticker: "LEN", name: "Lennar", reason: "Largest US homebuilder — lower mortgage rates directly unlock buyer demand" },
      { ticker: "DHI", name: "D.R. Horton", reason: "Volume builder with entry-level focus — most sensitive to affordability improvement" },
      { ticker: "IWM", name: "Russell 2000 ETF", reason: "Small caps are heavily leveraged; rate cuts reduce borrowing costs across the index" },
      { ticker: "VNQ", name: "Vanguard REIT ETF", reason: "REIT valuations are inverse to long rates — significant cap rate compression" },
      { ticker: "KRE", name: "SPDR Regional Banks ETF", reason: "Regional banks benefit from steeper yield curve and improved loan demand" },
      { ticker: "HD", name: "Home Depot", reason: "Housing activity and renovation spending pick up when rates drop" },
    ],
    avoid: [
      { ticker: "BRK.B", name: "Berkshire Hathaway", reason: "Insurance float earns less; Buffett's cash pile yields fall" },
      { ticker: "GLD", name: "SPDR Gold ETF", reason: "Partly a rates trade — may sell off as real rates normalize" },
    ],
    timeHorizon: "months",
    category: "monetary",
  },
  {
    id: "inflation-reignites",
    emoji: "🔥",
    title: "Inflation Reignites",
    thesis: "If CPI re-accelerates above 4%, the Fed reverses dovish expectations and real assets re-rate higher. Companies with pricing power and hard assets outperform. Long-duration growth stocks get crushed as discount rates rise again.",
    tags: ["Monetary Policy", "Macro"],
    keywords: ["inflation rises", "cpi hot", "core inflation", "inflation reaccelerates", "inflation surprise", "cpi surge", "inflation higher than expected", "prices rise"],
    long: [
      { ticker: "GLD", name: "SPDR Gold ETF", reason: "Classic inflation hedge — real rates fall as nominal rates lag" },
      { ticker: "XLE", name: "Energy Select Sector ETF", reason: "Energy is both an inflation cause and a beneficiary" },
      { ticker: "TIP", name: "iShares TIPS ETF", reason: "TIPS principal adjusts upward with CPI — direct inflation protection" },
      { ticker: "BRK.B", name: "Berkshire Hathaway", reason: "Insurance businesses reprice premiums; railroads and energy have pricing power" },
      { ticker: "WMT", name: "Walmart", reason: "Trade-down effect and pricing power; consumers shift to value" },
      { ticker: "COST", name: "Costco", reason: "Membership model locks in loyalty; bulk buying buffers inflation for consumers" },
    ],
    avoid: [
      { ticker: "TLT", name: "iShares 20+ Year Bond ETF", reason: "Long bonds are destroyed by rising rates" },
      { ticker: "IWM", name: "Russell 2000 ETF", reason: "Leveraged small caps suffer most as borrowing costs rise" },
    ],
    timeHorizon: "months",
    category: "monetary",
  },
  {
    id: "dollar-weakens",
    emoji: "💵",
    title: "US Dollar Weakens Significantly",
    thesis: "A weakening dollar lifts US multinationals' overseas earnings in dollar terms, boosts commodities priced in USD, and makes US exports more competitive. Emerging market equities and gold typically outperform in dollar downtrends.",
    tags: ["Currency", "Macro"],
    keywords: ["dollar weakness", "dollar decline", "usd falls", "dollar index", "dxy", "dollar selloff", "weaker dollar", "dollar bear"],
    long: [
      { ticker: "GLD", name: "SPDR Gold ETF", reason: "Gold is the inverse of the dollar — negative correlation is historically strong" },
      { ticker: "CAT", name: "Caterpillar", reason: "Global industrial — dollar-denominated products become cheaper for foreign buyers" },
      { ticker: "NEM", name: "Newmont Mining", reason: "Gold miner with global operations; earnings amplified by gold price rise" },
      { ticker: "FCX", name: "Freeport-McMoRan", reason: "Copper is priced in USD — weak dollar directly lifts realized prices" },
      { ticker: "EEM", name: "iShares EM ETF", reason: "Dollar-denominated EM debt cheapens; EM risk assets broadly rally" },
      { ticker: "BA", name: "Boeing", reason: "Aircraft are priced in dollars — foreign buyers' effective cost falls" },
    ],
    avoid: [
      { ticker: "UUP", name: "Invesco DB Dollar Bullish ETF", reason: "Direct long-dollar instrument — inverse trade" },
    ],
    timeHorizon: "months",
    category: "monetary",
  },

  // ─── GEOPOLITICAL ───────────────────────────────────────────────────────────
  {
    id: "china-taiwan-escalation",
    emoji: "🚨",
    title: "China-Taiwan Military Escalation",
    thesis: "Military posturing around Taiwan triggers a semiconductor supply chain crisis and flight to US defense assets. TSMC is the single point of failure for advanced chips — any production disruption would be catastrophic. Defense budgets globally would surge overnight.",
    tags: ["Geopolitical", "Defense", "Semiconductors"],
    keywords: ["taiwan", "china military", "pla exercises", "china taiwan", "taiwan strait", "taiwan invasion", "taiwan blockade", "taiwan conflict"],
    long: [
      { ticker: "LMT", name: "Lockheed Martin", reason: "F-35 and missile systems would see immediate order surge from US and allies" },
      { ticker: "RTX", name: "RTX Corp", reason: "Missile defense and radar systems — a Taiwan scenario drives NATO-wide rearmament" },
      { ticker: "NOC", name: "Northrop Grumman", reason: "B-21 bomber program and nuclear command systems in high demand" },
      { ticker: "GD", name: "General Dynamics", reason: "Shipbuilding and military vehicles — Pacific theater defense buildup" },
      { ticker: "INTC", name: "Intel", reason: "US push for onshore advanced chip manufacturing accelerates dramatically" },
      { ticker: "ONTO", name: "Onto Innovation", reason: "Semiconductor metrology — critical for any domestic fab buildout" },
    ],
    avoid: [
      { ticker: "AAPL", name: "Apple", reason: "85%+ of iPhone production is in China; supply chain risk is existential" },
      { ticker: "TSM", name: "TSMC ADR", reason: "Direct risk to the physical fab infrastructure" },
    ],
    timeHorizon: "months",
    category: "geopolitical",
  },
  {
    id: "ukraine-peace",
    emoji: "🕊️",
    title: "Russia-Ukraine Peace Deal",
    thesis: "A ceasefire unlocks a European reconstruction supercycle. Steel, cement, infrastructure, and logistics companies operating in or supplying Europe are immediate beneficiaries. Natural gas prices normalize and European utilities re-rate. Defense contractors give back some premium.",
    tags: ["Geopolitical", "Europe", "Infrastructure"],
    keywords: ["ukraine ceasefire", "ukraine peace", "russia ukraine deal", "ukraine negotiations", "peace talks ukraine", "end ukraine war", "ceasefire ukraine"],
    long: [
      { ticker: "MT", name: "ArcelorMittal", reason: "World's largest steelmaker — European reconstruction drives structural demand" },
      { ticker: "VMC", name: "Vulcan Materials", reason: "Aggregates for infrastructure construction; European supply is tight post-war" },
      { ticker: "NTR", name: "Nutrien", reason: "Black Sea grain flows resume; fertilizer market normalizes from wartime disruptions" },
      { ticker: "EWG", name: "iShares Germany ETF", reason: "Germany is the industrial anchor of European reconstruction" },
      { ticker: "DE", name: "Deere & Co", reason: "Agricultural equipment demand surges as Ukrainian farmland returns to production" },
    ],
    avoid: [
      { ticker: "LMT", name: "Lockheed Martin", reason: "European defense urgency fades; F-35 order pipeline may slow" },
      { ticker: "RTX", name: "RTX Corp", reason: "Same dynamic — war-premium unwinds" },
    ],
    timeHorizon: "months",
    category: "geopolitical",
  },
  {
    id: "us-defense-surge",
    emoji: "🛡️",
    title: "US Defense Budget Surge",
    thesis: "NATO commitments, Pacific theater competition, or a major geopolitical event drives a multi-year US defense spending increase. This is a long-duration contract business — once funding is authorized, backlogs fill for years.",
    tags: ["Defense", "Geopolitical"],
    keywords: ["defense spending", "military budget", "nato funding", "defense contract", "pentagon budget", "defense authorization", "national security spending", "military spending"],
    long: [
      { ticker: "LMT", name: "Lockheed Martin", reason: "F-35, hypersonics, missile defense — dominant position in every growth area" },
      { ticker: "RTX", name: "RTX Corp", reason: "Patriot missile systems are in unprecedented global demand" },
      { ticker: "NOC", name: "Northrop Grumman", reason: "B-21, space systems, and nuclear modernization contracts" },
      { ticker: "GD", name: "General Dynamics", reason: "Submarine and destroyer programs have decade-long backlogs" },
      { ticker: "AXON", name: "Axon Enterprise", reason: "Defense tech expansion into surveillance and connected officer systems" },
      { ticker: "SAIC", name: "Science Applications Int'l", reason: "IT and logistics for defense; grows with DoD budget broadly" },
    ],
    avoid: [],
    timeHorizon: "years",
    category: "geopolitical",
  },

  // ─── TECHNOLOGY ─────────────────────────────────────────────────────────────
  {
    id: "ai-acceleration",
    emoji: "🤖",
    title: "AI Spending Acceleration Continues",
    thesis: "Hyperscalers keep ratcheting up AI capex beyond consensus expectations. Power and cooling become the binding constraint — utilities and data center operators are structurally undervalued. Nvidia is the obvious winner but the real alpha is in the picks-and-shovels: power, cooling, and custom silicon.",
    tags: ["Technology", "AI"],
    keywords: ["ai capex", "ai investment", "data center", "gpu demand", "artificial intelligence spending", "ai infrastructure", "hyperscaler capex", "nvidia demand", "ai compute", "ai buildout"],
    long: [
      { ticker: "NVDA", name: "Nvidia", reason: "GPU monopoly for training and inference — every dollar of AI capex flows through here" },
      { ticker: "CEG", name: "Constellation Energy", reason: "Nuclear power under 20-year data center contracts; massive earnings visibility" },
      { ticker: "VST", name: "Vistra Energy", reason: "Signed hyperscaler power deals; stock has multi-year earnings re-rating ahead" },
      { ticker: "SMCI", name: "Super Micro Computer", reason: "Custom AI server systems — sells directly to hyperscalers with fast design cycles" },
      { ticker: "CDNS", name: "Cadence Design Systems", reason: "EDA software is required for every custom AI chip design at any foundry" },
      { ticker: "AMD", name: "AMD", reason: "MI300X GPU gaining share in inference; second source to Nvidia in every hyperscaler" },
    ],
    avoid: [
      { ticker: "INTC", name: "Intel", reason: "Losing foundry and GPU market share simultaneously; execution risks are high" },
    ],
    timeHorizon: "months",
    category: "tech",
  },
  {
    id: "ai-bubble-deflates",
    emoji: "📉",
    title: "AI Capex Bubble Deflates",
    thesis: "If hyperscalers cut or delay AI infrastructure spend — due to ROI disappointment, capacity glut, or regulatory pressure — the entire AI supply chain gets re-rated. Nvidia's P/E goes from pricing perfection to pricing reality. The companies that can't show monetization get hit hardest.",
    tags: ["Technology", "AI"],
    keywords: ["ai bubble", "ai hype cycle", "capex cuts", "ai spending cuts", "ai returns disappointing", "ai revenue miss", "ai layoffs", "ai pause", "capex reduction"],
    long: [
      { ticker: "MSFT", name: "Microsoft", reason: "Azure cloud growth is AI-agnostic; enterprise software is recurring and defensive" },
      { ticker: "ORCL", name: "Oracle", reason: "Databases are infrastructure — not exposed to AI speculation premium" },
      { ticker: "INTU", name: "Intuit", reason: "Tax and SMB software — recession-resistant recurring revenue, no AI premium" },
    ],
    avoid: [
      { ticker: "NVDA", name: "Nvidia", reason: "Priced for 40%+ revenue growth for multiple years — any slowdown is catastrophic" },
      { ticker: "SMCI", name: "Super Micro Computer", reason: "Pure-play on AI server demand; fastest to fall if capex disappoints" },
      { ticker: "IREN", name: "IREN Ltd", reason: "Bitcoin miner pivoting to AI compute — highly speculative, no moat" },
    ],
    timeHorizon: "weeks",
    category: "tech",
  },
  {
    id: "semiconductor-glut",
    emoji: "💾",
    title: "Semiconductor Supply Glut",
    thesis: "Overcapacity from the 2021-2023 fab expansion cycle hits the market. Memory chips lead the downturn as average selling prices collapse. Fabless chip designers that sell differentiated products fare better than commodity manufacturers.",
    tags: ["Technology", "Semiconductors"],
    keywords: ["chip glut", "semiconductor inventory", "chip oversupply", "memory glut", "wafer inventory", "semiconductor pricing", "chip prices fall", "chip oversupply"],
    long: [
      { ticker: "AAPL", name: "Apple", reason: "Owns its silicon design; not exposed to commodity chip pricing" },
      { ticker: "QCOM", name: "Qualcomm", reason: "Premium mobile SoC designer — pricing power through brand differentiation" },
      { ticker: "AMAT", name: "Applied Materials", reason: "Equipment orders lag cycle; can be defensive if glut is priced in" },
    ],
    avoid: [
      { ticker: "MU", name: "Micron Technology", reason: "DRAM and NAND pricing is directly linked to supply/demand; biggest casualty" },
      { ticker: "INTC", name: "Intel", reason: "Commodity CPU/data center chips lose pricing power in a glut" },
      { ticker: "AMD", name: "AMD", reason: "Server CPU market share gains stall as buyers pause in oversupply environment" },
    ],
    timeHorizon: "months",
    category: "tech",
  },
  {
    id: "cybersecurity-surge",
    emoji: "🔐",
    title: "Major Cybersecurity Attack Wave",
    thesis: "A high-profile breach or attack on critical infrastructure triggers an emergency wave of government and enterprise security spending. History shows that after major incidents, budgets open immediately — this is one of the only sectors with truly non-cyclical spend.",
    tags: ["Technology", "Security"],
    keywords: ["cyberattack", "data breach", "ransomware", "critical infrastructure attack", "cybersecurity incident", "hack attack", "state-sponsored hack", "cyber warfare"],
    long: [
      { ticker: "CRWD", name: "CrowdStrike", reason: "Market leader in endpoint security and threat intelligence — first call after any breach" },
      { ticker: "PANW", name: "Palo Alto Networks", reason: "Platform approach means more wallet share per enterprise customer" },
      { ticker: "ZS", name: "Zscaler", reason: "Zero-trust networking — becomes the architecture of choice post-breach" },
      { ticker: "FTNT", name: "Fortinet", reason: "Strong in OT/ICS security — critical infrastructure attacks are its sweet spot" },
      { ticker: "S", name: "SentinelOne", reason: "AI-native detection platform; benefits from CRWD share wins and greenfield" },
    ],
    avoid: [],
    timeHorizon: "weeks",
    category: "tech",
  },

  // ─── ECONOMY ────────────────────────────────────────────────────────────────
  {
    id: "us-recession",
    emoji: "📊",
    title: "US Recession Confirmed",
    thesis: "GDP contracts for two quarters, unemployment rises above 5%, and consumer spending falls. Defensive consumer staples, healthcare, and utilities hold value. High-quality bonds rally. The companies that fall the most are those with high leverage and cyclical revenue.",
    tags: ["Macro", "Economy"],
    keywords: ["recession", "gdp contraction", "economic slowdown", "unemployment rise", "layoffs surge", "negative growth", "recession confirmed", "recession fears", "gdp negative"],
    long: [
      { ticker: "KO", name: "Coca-Cola", reason: "Beverage consumption is non-discretionary — one of the most recession-proof businesses" },
      { ticker: "PG", name: "Procter & Gamble", reason: "Household staples with 130+ years of dividend history" },
      { ticker: "JNJ", name: "Johnson & Johnson", reason: "Healthcare + medtech = demand doesn't go away in a recession" },
      { ticker: "TLT", name: "iShares 20+ Year Bond ETF", reason: "Flight to safety drives bond prices up as yields fall" },
      { ticker: "DG", name: "Dollar General", reason: "Trade-down effect — consumers shift to deep-discount retail" },
      { ticker: "GLD", name: "SPDR Gold ETF", reason: "Safe haven demand and likely Fed response (cuts) both boost gold" },
    ],
    avoid: [
      { ticker: "AMZN", name: "Amazon", reason: "Retail and advertising revenue both cyclical; AWS can hold but stock has high multiple" },
      { ticker: "KRE", name: "SPDR Regional Banks ETF", reason: "Credit losses surge in recessions; commercial real estate exposure is particularly dangerous" },
    ],
    timeHorizon: "months",
    category: "economy",
  },
  {
    id: "soft-landing",
    emoji: "🛬",
    title: "Soft Landing Confirmed",
    thesis: "Inflation normalizes, the Fed can ease, and the economy avoids contraction. This is the goldilocks outcome that most risk assets are not fully pricing. Cyclicals and small caps get a growth + rate relief double boost. Safe havens unwind.",
    tags: ["Macro", "Economy"],
    keywords: ["soft landing", "no recession", "goldilocks", "inflation target", "cpi falls", "jobs report strong", "economy resilient", "gdp beat", "growth beats"],
    long: [
      { ticker: "IWM", name: "Russell 2000 ETF", reason: "Small caps are leveraged to growth + rates; biggest winner in goldilocks" },
      { ticker: "XLY", name: "Consumer Discretionary ETF", reason: "Consumer spending stays strong; travel, retail, autos all benefit" },
      { ticker: "XLF", name: "Financial Sector ETF", reason: "Banks benefit from loan growth without credit losses" },
      { ticker: "LEN", name: "Lennar", reason: "Housing recovers as rates ease and confidence returns" },
      { ticker: "SPY", name: "S&P 500 ETF", reason: "Broad market lift — minimal reason to be selective, buy the index" },
    ],
    avoid: [
      { ticker: "GLD", name: "SPDR Gold ETF", reason: "Risk-off safe haven trade unwinds as recession fears fade" },
      { ticker: "TLT", name: "iShares 20+ Year Bond ETF", reason: "Less flight-to-safety demand; rates normalize rather than plunge" },
    ],
    timeHorizon: "months",
    category: "economy",
  },
  {
    id: "consumer-slowdown",
    emoji: "💳",
    title: "Consumer Spending Slowdown",
    thesis: "Savings buffers are exhausted and credit card delinquencies rise. Discretionary spending falls first — restaurants, travel, luxury. Value retailers and essential services hold or gain share. This tends to play out over 6-12 months before full recession signals appear.",
    tags: ["Economy", "Consumer"],
    keywords: ["consumer spending", "retail sales fall", "consumer confidence", "credit card debt", "consumer slowdown", "delinquencies rise", "spending drops", "savings rate falls"],
    long: [
      { ticker: "DG", name: "Dollar General", reason: "Benefit from trade-down as consumers seek lowest prices" },
      { ticker: "DLTR", name: "Dollar Tree", reason: "Same trade-down dynamic; also includes Family Dollar for grocery" },
      { ticker: "WMT", name: "Walmart", reason: "Every slowdown adds Walmart share — it is the value destination" },
      { ticker: "MCD", name: "McDonald's", reason: "QSR trade-down from sit-down dining is reliable and fast" },
      { ticker: "KO", name: "Coca-Cola", reason: "People stop going out but keep buying beverages — pricing power intact" },
    ],
    avoid: [
      { ticker: "RH", name: "RH (Restoration Hardware)", reason: "High-end home furnishing — first purchase to be deferred in a slowdown" },
      { ticker: "ABNB", name: "Airbnb", reason: "Leisure travel is early-cycle discretionary — demand softens quickly" },
    ],
    timeHorizon: "months",
    category: "economy",
  },
  {
    id: "housing-recovery",
    emoji: "🏠",
    title: "Housing Market Recovery",
    thesis: "Mortgage rates decline meaningfully and/or housing inventory improves, unlocking the 'lock-in effect.' Existing home sales have been historically depressed — even a modest rate move could release years of pent-up demand. Homebuilders, home improvement, and proptech all benefit.",
    tags: ["Economy", "Real Estate"],
    keywords: ["housing recovery", "home sales", "mortgage rates fall", "housing starts", "homebuilder orders", "housing inventory", "existing home sales", "real estate recovery"],
    long: [
      { ticker: "DHI", name: "D.R. Horton", reason: "Largest US homebuilder by volume; entry-level focus serves the most demand-constrained segment" },
      { ticker: "LEN", name: "Lennar", reason: "Geographic diversification and financial services arm provide earnings stability" },
      { ticker: "PHM", name: "PulteGroup", reason: "Move-up buyer focus benefits most from inventory unlock" },
      { ticker: "HD", name: "Home Depot", reason: "Existing home sales drive renovation spend — each sale triggers 3-5 years of projects" },
      { ticker: "LOW", name: "Lowe's", reason: "Same renovation dynamic; increasingly focused on pro contractor market" },
    ],
    avoid: [],
    timeHorizon: "months",
    category: "economy",
  },

  // ─── POLICY ────────────────────────────────────────────────────────────────
  {
    id: "trade-war-escalates",
    emoji: "🚧",
    title: "Trade War Escalates",
    thesis: "New broad tariffs and retaliatory measures disrupt global supply chains. Domestic producers gain pricing power while importers face margin compression. The reshoring narrative accelerates — companies that have already moved manufacturing to the US or Mexico are insulated.",
    tags: ["Policy", "Geopolitical"],
    keywords: ["tariff", "trade war", "trade barrier", "import duty", "trade dispute", "trade sanctions", "trade restrictions", "china tariff", "tariff hike"],
    long: [
      { ticker: "NUE", name: "Nucor", reason: "Domestic steel producer — tariffs on imports directly improve pricing and market share" },
      { ticker: "X", name: "US Steel", reason: "Same steel tariff logic; higher beta to trade war developments" },
      { ticker: "HON", name: "Honeywell", reason: "Domestic industrial with government and aerospace exposure; reshoring beneficiary" },
      { ticker: "GEV", name: "GE Vernova", reason: "Power grid infrastructure — domestic production increasingly required by policy" },
      { ticker: "CAT", name: "Caterpillar", reason: "Infrastructure spend is tariff-linked; equipment is domestically manufactured" },
    ],
    avoid: [
      { ticker: "NKE", name: "Nike", reason: "Vietnam and China manufacturing; tariffs hit margins immediately" },
      { ticker: "AAPL", name: "Apple", reason: "China assembly — any tariff escalation forces expensive supply chain restructuring" },
    ],
    timeHorizon: "weeks",
    category: "policy",
  },
  {
    id: "renewable-policy-boost",
    emoji: "🌱",
    title: "Renewable Energy Policy Boost",
    thesis: "New subsidies, tax credits, or regulatory mandates accelerate the energy transition. Solar and wind developers see project economics improve overnight. Utilities with renewable pipelines re-rate upward as their future earnings become more visible.",
    tags: ["Policy", "Energy"],
    keywords: ["clean energy", "renewable energy", "solar policy", "wind energy", "energy transition", "green deal", "ira extension", "clean power plan", "renewable incentive", "carbon credit"],
    long: [
      { ticker: "FSLR", name: "First Solar", reason: "US-made solar panels — directly benefits from domestic manufacturing credits" },
      { ticker: "NEE", name: "NextEra Energy", reason: "World's largest renewable energy producer; largest pipeline of wind and solar projects" },
      { ticker: "ENPH", name: "Enphase Energy", reason: "Microinverter technology dominant in residential solar — ITC extension expands market" },
      { ticker: "BEP", name: "Brookfield Renewable", reason: "Global renewable developer; policy support improves project economics globally" },
      { ticker: "CWEN", name: "Clearway Energy", reason: "Contracted renewable energy — regulated returns with policy tailwind" },
    ],
    avoid: [
      { ticker: "XOM", name: "Exxon Mobil", reason: "Policy headwinds for new fossil fuel development increase regulatory costs" },
    ],
    timeHorizon: "months",
    category: "policy",
  },
  {
    id: "tech-antitrust",
    emoji: "⚖️",
    title: "Big Tech Antitrust Crackdown",
    thesis: "DOJ or FTC enforcement actions against Google, Meta, Amazon, or Apple create structural overhang on ad-based and platform business models. Enterprise software and infrastructure businesses that are not antitrust targets benefit from portfolio rotation.",
    tags: ["Policy", "Technology"],
    keywords: ["antitrust", "tech regulation", "big tech regulation", "doj", "ftc", "tech monopoly", "break up", "market dominance", "platform regulation"],
    long: [
      { ticker: "INTU", name: "Intuit", reason: "SMB and tax software — not a platform business, no antitrust exposure" },
      { ticker: "ADBE", name: "Adobe", reason: "Creative software with strong subscription moats; not in antitrust crosshairs" },
      { ticker: "ORCL", name: "Oracle", reason: "Enterprise database and cloud; benefits from rotation away from big platform tech" },
    ],
    avoid: [
      { ticker: "GOOG", name: "Alphabet", reason: "Search monopoly is the core antitrust case — remedies could be structural" },
      { ticker: "META", name: "Meta Platforms", reason: "Instagram acquisition reversal is the live risk; advertising model under scrutiny" },
    ],
    timeHorizon: "months",
    category: "policy",
  },

  // ─── MARKETS ────────────────────────────────────────────────────────────────
  {
    id: "market-correction",
    emoji: "📉",
    title: "Equity Market Correction (10%+)",
    thesis: "Whether triggered by valuation, macro surprise, or a black swan, a 10-15% correction is the buy-the-dip setup for quality compounders. The key is identifying which names hold best on the way down — those are the ones with the best risk/reward on the bounce.",
    tags: ["Markets", "Volatility"],
    keywords: ["market selloff", "market correction", "stocks fall", "equity decline", "market crash", "bear market", "risk-off", "market drop", "vix spike", "sell stocks"],
    long: [
      { ticker: "BRK.B", name: "Berkshire Hathaway", reason: "Defensive compounding business with $150B+ cash — Buffett deploys capital in corrections" },
      { ticker: "MSFT", name: "Microsoft", reason: "Cloud + software = recurring revenue; correction creates entry into a premium business" },
      { ticker: "AAPL", name: "Apple", reason: "Services business is highly recurring; ecosystem lock-in is unmatched" },
      { ticker: "GLD", name: "SPDR Gold ETF", reason: "Safe haven demand surges in equity corrections" },
      { ticker: "VIX", name: "CBOE Volatility Index", reason: "Volatility instruments (UVXY, VIXY) spike — useful hedge or short-term trade" },
    ],
    avoid: [
      { ticker: "ARKK", name: "ARK Innovation ETF", reason: "High-beta, high-multiple speculative tech — first and hardest to fall" },
      { ticker: "MSTR", name: "MicroStrategy", reason: "Bitcoin proxy; extreme beta to risk-off conditions" },
    ],
    timeHorizon: "weeks",
    category: "markets",
  },
  {
    id: "credit-crunch",
    emoji: "🏦",
    title: "Banking Stress / Credit Crunch",
    thesis: "Bank failures or a sharp tightening in lending standards reduce credit availability across the economy. Commercial real estate is the most likely catalyst — office and retail portfolios with regional banks are already stressed. When credit freezes, cash-rich companies and defensive sectors dramatically outperform.",
    tags: ["Markets", "Finance"],
    keywords: ["bank failure", "credit crunch", "banking stress", "bank crisis", "credit tightening", "bank collapse", "commercial real estate", "cre losses", "bank run"],
    long: [
      { ticker: "KO", name: "Coca-Cola", reason: "Zero credit dependency; pure operating cash flow generation" },
      { ticker: "PG", name: "Procter & Gamble", reason: "AAA-rated balance sheet; consumer demand is non-cyclical" },
      { ticker: "GLD", name: "SPDR Gold ETF", reason: "Flight to safety is strongest when financial system stress is acute" },
      { ticker: "TLT", name: "iShares 20+ Year Bond ETF", reason: "Banking stress forces Fed response; flight to treasuries is immediate" },
      { ticker: "JPM", name: "JPMorgan Chase", reason: "Largest US bank with strongest balance sheet — gains deposits from weaker banks" },
    ],
    avoid: [
      { ticker: "KRE", name: "SPDR Regional Banks ETF", reason: "Regional banks are the epicenter of CRE stress" },
      { ticker: "VNQ", name: "Vanguard REIT ETF", reason: "Commercial real estate is the first casualty of credit tightening" },
    ],
    timeHorizon: "weeks",
    category: "markets",
  },
  {
    id: "china-stimulus",
    emoji: "🐉",
    title: "China Unleashes Major Stimulus",
    thesis: "The PBOC and Chinese government deploy a broad stimulus package — infrastructure, consumer, or property. This is the most reliable way to move commodity prices and EM equities simultaneously. US multinationals with China exposure snap back; commodities rally on anticipated demand.",
    tags: ["Economy", "China", "Commodities"],
    keywords: ["china stimulus", "china economic", "pboc easing", "china gdp", "china growth", "china recovery", "china policy support", "china bailout", "chinese stimulus"],
    long: [
      { ticker: "FCX", name: "Freeport-McMoRan", reason: "China is 55% of global copper demand — stimulus directly lifts copper prices" },
      { ticker: "CLF", name: "Cleveland-Cliffs", reason: "US steel prices historically track Chinese steel activity with a lag" },
      { ticker: "VALE", name: "Vale ADR", reason: "World's largest iron ore producer; China buys 70%+ of seaborne iron ore" },
      { ticker: "FXI", name: "iShares China Large-Cap ETF", reason: "Direct exposure to Chinese equity market re-rating" },
      { ticker: "LVS", name: "Las Vegas Sands", reason: "Macau gaming revenues track Chinese consumer confidence directly" },
    ],
    avoid: [],
    timeHorizon: "weeks",
    category: "economy",
  },
  {
    id: "commodity-supercycle",
    emoji: "⛏️",
    title: "Commodity Supercycle Resumes",
    thesis: "Underinvestment in mining and energy through the 2010s, combined with electrification and AI infrastructure demand, creates multi-year supply deficits in copper, uranium, silver, and critical minerals. These supply gaps take years to close — the setup for a prolonged bull market in commodities.",
    tags: ["Commodities", "Infrastructure"],
    keywords: ["commodity supercycle", "copper demand", "infrastructure spending", "copper shortage", "mining", "critical minerals", "copper deficit", "commodity boom", "raw materials"],
    long: [
      { ticker: "FCX", name: "Freeport-McMoRan", reason: "Largest publicly traded copper miner; copper is critical for electrification" },
      { ticker: "CCJ", name: "Cameco", reason: "Nuclear uranium producer — power demand drives uranium deficit for decades" },
      { ticker: "GLD", name: "SPDR Gold ETF", reason: "Gold is a broad commodity supercycle beneficiary and inflation hedge" },
      { ticker: "SLV", name: "iShares Silver ETF", reason: "Silver has industrial demand (solar panels, EVs) on top of monetary demand" },
      { ticker: "NEM", name: "Newmont Mining", reason: "Gold miner with global portfolio — operational leverage to gold price" },
      { ticker: "BHP", name: "BHP Group ADR", reason: "Diversified mining giant with iron ore, copper, and potash exposure" },
    ],
    avoid: [],
    timeHorizon: "years",
    category: "markets",
  },
];
