export const STARTER_STRATEGIES = [
  {
    name: "Balanced Growth",
    emoji: "⚖️",
    tagline: "Steady growth, managed risk",
    description: "Diversified across sectors with moderate volatility. A solid foundation for most investors.",
    style: "balanced",
    risk_level: "moderate",
    prompt_text: "Balanced portfolio targeting consistent 10–15% annual returns. Prioritize quality companies with steady revenue growth and reasonable valuations. No single position above 15%. Mix of growth (60%) and value (40%). Maintain 5–15% cash. Sectors: Technology, Healthcare, Consumer, Financials.",
    max_position_pct: 15,
    min_position_pct: 2,
    cash_min_pct: 5,
    cash_max_pct: 15,
    turnover_preference: "medium",
    holding_period_bias: "medium_term",
  },
  {
    name: "Long-Term Compounder",
    emoji: "🌱",
    tagline: "Buy quality, hold for years",
    description: "Exceptional businesses with durable advantages. Built for 5+ year horizons with minimal turnover.",
    style: "value",
    risk_level: "conservative",
    prompt_text: "Long-term portfolio targeting exceptional businesses with wide economic moats. Consistent free cash flow, durable competitive advantages, strong management. Positions held for years. Max 20% in any single established holding. Minimize turnover. Sectors: Technology, Consumer Staples, Healthcare, Financial Services.",
    max_position_pct: 20,
    min_position_pct: 3,
    cash_min_pct: 5,
    cash_max_pct: 10,
    turnover_preference: "low",
    holding_period_bias: "long_term",
  },
  {
    name: "Aggressive Growth",
    emoji: "🚀",
    tagline: "High conviction, high upside",
    description: "Concentrated bets on high-growth companies. Higher volatility in exchange for higher return potential.",
    style: "growth",
    risk_level: "aggressive",
    prompt_text: "Aggressive portfolio targeting 20%+ annual returns. Focus on high-growth companies with rapidly expanding revenue and large addressable markets. Accept elevated volatility. 10–15 concentrated positions. Sectors: Technology, Biotech, Fintech, AI. Trim losers quickly, let winners run. Cash up to 20% for dip deployment.",
    max_position_pct: 20,
    min_position_pct: 3,
    cash_min_pct: 5,
    cash_max_pct: 20,
    turnover_preference: "high",
    holding_period_bias: "short_term",
  },
  {
    name: "Dividend Focus",
    emoji: "💰",
    tagline: "Consistent income stream",
    description: "Reliable dividend payers for steady income and capital preservation. Suited for income-oriented investors.",
    style: "income",
    risk_level: "conservative",
    prompt_text: "Income portfolio targeting 4–6% annual dividend yield. Companies with 5+ year dividend growth history, sustainable payout ratios (<70%), and strong balance sheets. Sectors: Utilities, Consumer Staples, REITs, Healthcare, Financials. Focus on dividend quality over raw yield. Max 10% per position.",
    max_position_pct: 10,
    min_position_pct: 2,
    cash_min_pct: 3,
    cash_max_pct: 10,
    turnover_preference: "low",
    holding_period_bias: "long_term",
  },
  {
    name: "AI Momentum",
    emoji: "⚡",
    tagline: "Ride the AI wave",
    description: "Focused on AI infrastructure, software, and enablers. A thematic strategy for the current tech cycle.",
    style: "thematic",
    risk_level: "aggressive",
    prompt_text: "Thematic portfolio focused on AI infrastructure, software, and services. Target companies directly monetizing AI demand: chip makers, cloud providers, AI software platforms, enterprise AI adopters. Track momentum and rotate on fundamental shifts. Max 15% per position. Sectors: Semiconductors, Cloud, AI Software, Data Infrastructure.",
    max_position_pct: 15,
    min_position_pct: 3,
    cash_min_pct: 5,
    cash_max_pct: 20,
    turnover_preference: "medium",
    holding_period_bias: "medium_term",
  },
] as const;
