import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/app/components/theme-provider";
import PWARegister from "@/app/components/pwa-register";
import MobileBottomNav from "@/app/components/mobile-bottom-nav";
import IosInstallGuide from "@/app/components/ios-install-guide";
import LevelUpWatcher from "@/app/components/level-up-watcher";
import BehavioralGuardrail from "@/app/components/behavioral-guardrail";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL ?? "https://buytune.io"),
  title: "BuyTune.io — AI-Powered Portfolio Analysis",
  description: "Institutional-grade AI investing insights, personalized to your strategy and risk profile.",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "BuyTune",
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    title: "BuyTune.io — AI Portfolio Analysis",
    description: "Institutional-grade AI investing insights, personalized to your strategy.",
    type: "website",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Extend under the notch/status bar so we can paint that area with the brand color
  // (the black-translucent status bar would otherwise let scrolled content show through it).
  viewportFit: "cover",
  themeColor: "#07090f",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* iPhone home-screen icon is generated by app/apple-icon.tsx (full-bleed, no gaps). */}
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="BuyTune" />
      </head>
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <PWARegister />
          {children}
          <MobileBottomNav />
          <IosInstallGuide />
          <LevelUpWatcher />
          <BehavioralGuardrail />
          <Analytics />
          <SpeedInsights />
        </ThemeProvider>
      </body>
    </html>
  );
}
