import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Syne, DM_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/app/components/theme-provider";
import PWARegister from "@/app/components/pwa-register";
import MobileBottomNav from "@/app/components/mobile-bottom-nav";
import IosInstallGuide from "@/app/components/ios-install-guide";
import LevelUpWatcher from "@/app/components/level-up-watcher";
import ActivityTracker from "@/app/components/activity-tracker";
import CacheWarmer from "@/app/components/cache-warmer";
import BehavioralGuardrail from "@/app/components/behavioral-guardrail";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Syne is deliberately wide — great as a small wordmark accent, overwhelming as
// large headings. It now feeds only the --font-logo token; headings run on DM Sans.
const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
  weight: ["700", "800"],
  display: "swap",
});

// Self-hosted DM Sans (variable weights) with a metric-matched fallback — powers
// both --font-body and --font-display so headings and body never FOUT-shift.
const dmSans = DM_Sans({
  variable: "--font-dm",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL ?? "https://buytune.io"),
  title: "BuyTune.io — AI-Powered Portfolio Analysis",
  description: "Institutional-grade AI investing insights, personalized to your strategy and risk profile.",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "BuyTune",
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    title: "BuyTune.io — AI Portfolio Analysis",
    description: "Institutional-grade AI investing insights, personalized to your strategy.",
    type: "website",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Users must be able to zoom (WCAG 1.4.4) — never lock the scale.
  maximumScale: 5,
  userScalable: true,
  // Extend under the notch/status bar so we can paint that area with the brand color
  // (the black-translucent status bar would otherwise let scrolled content show through it).
  viewportFit: "cover",
  themeColor: "#07090f",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${syne.variable} ${dmSans.variable} h-full antialiased`}
    >
      <head>
        {/* iPhone home-screen icon is generated by app/apple-icon.tsx (full-bleed, no gaps). */}
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="BuyTune" />
      </head>
      <body className="min-h-full flex flex-col">
        {/* Keyboard users jump past the persistent chrome straight to page content. */}
        <a href="#bt-content" className="bt-skip-link">Skip to main content</a>
        <ThemeProvider>
          <PWARegister />
          <div id="bt-content" style={{ display: "contents" }}>{children}</div>
          <MobileBottomNav />
          <IosInstallGuide />
          <LevelUpWatcher />
          <ActivityTracker />
          <CacheWarmer />
          <BehavioralGuardrail />
          <Analytics />
          <SpeedInsights />
        </ThemeProvider>
      </body>
    </html>
  );
}
