export const metadata = { title: "Terms of Service — BuyTune" };

const EFFECTIVE = "May 26, 2026";

export default function TermsPage() {
  return (
    <article>
      <div style={{ marginBottom: "32px" }}>
        <div style={{ fontSize: "10px", fontWeight: 700, color: "#2563eb", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: "8px" }}>Legal</div>
        <h1 style={{ fontFamily: "var(--font-display)", fontSize: "28px", fontWeight: 700, color: "#f1f5f9", letterSpacing: "-0.5px", marginBottom: "8px" }}>Terms of Service</h1>
        <p style={{ fontSize: "13px", color: "var(--text-tertiary)" }}>Effective date: {EFFECTIVE} &nbsp;·&nbsp; Governing law: Texas, United States</p>
      </div>

      <div style={{ padding: "14px 18px", background: "rgba(37,99,235,0.07)", border: "1px solid rgba(37,99,235,0.18)", borderRadius: "10px", marginBottom: "32px" }}>
        <p style={{ fontSize: "13px", color: "#93c5fd", lineHeight: 1.7 }}>
          <strong>Important:</strong> BuyTune is educational and analytical software. It is not a registered investment advisor, broker-dealer, or fiduciary. Nothing on this platform constitutes investment advice. Please read these terms carefully before using the platform.
        </p>
      </div>

      <section className="legal-section">
        <h2 className="legal-h2">1. Agreement to Terms</h2>
        <p className="legal-p">By accessing or using BuyTune.io ("BuyTune," "we," "us," or "the platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the platform.</p>
        <p className="legal-p">We may update these Terms at any time. Continued use after changes constitutes acceptance of the revised Terms. We will notify users of material changes by updating the effective date above.</p>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">2. Description of Service</h2>
        <p className="legal-p">BuyTune is an AI-powered portfolio analysis and financial planning platform. The platform provides:</p>
        <ul className="legal-ul">
          <li>Portfolio tracking, analysis, and visualization</li>
          <li>AI-generated investment observations and portfolio insights</li>
          <li>Financial planning tools including retirement projections and cash flow modeling</li>
          <li>Market data, stock research, and educational content</li>
          <li>Community features for sharing portfolio strategies</li>
        </ul>
        <p className="legal-p">All outputs are for <strong>educational and informational purposes only</strong>. BuyTune does not execute trades, manage assets, or provide personalized investment advice.</p>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">3. Educational Use Only — No Investment Advice</h2>
        <p className="legal-p">BuyTune is <strong>not a registered investment advisor</strong> under the Investment Advisers Act of 1940 or any state securities law. BuyTune is <strong>not a broker-dealer</strong> registered with the SEC or FINRA. BuyTune does <strong>not</strong> provide:</p>
        <ul className="legal-ul">
          <li>Personalized investment advice</li>
          <li>Recommendations to buy, sell, or hold any specific security</li>
          <li>Portfolio management services</li>
          <li>Financial planning advice</li>
          <li>Tax or legal advice</li>
        </ul>
        <p className="legal-p">Any analysis, score, recommendation, or projection generated by BuyTune is an <strong>AI-generated educational illustration</strong>. You are solely responsible for all investment and financial decisions you make. You should consult a licensed financial advisor, tax professional, or attorney before making significant financial decisions.</p>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">4. No Fiduciary Relationship</h2>
        <p className="legal-p">No fiduciary, advisory, or agency relationship exists between BuyTune and any user. BuyTune has no duty to act in your financial interest, and no such duty should be implied from use of the platform.</p>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">5. AI-Generated Content Disclaimer</h2>
        <p className="legal-p">BuyTune uses artificial intelligence to generate analysis, recommendations, projections, and insights. You acknowledge that AI-generated content:</p>
        <ul className="legal-ul">
          <li>May contain errors, inaccuracies, or omissions</li>
          <li>May not reflect current market conditions</li>
          <li>Is based on historical data and statistical models, not guaranteed future outcomes</li>
          <li>Should not be the sole basis for any financial decision</li>
          <li>Is not a substitute for professional financial, legal, or tax advice</li>
        </ul>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">6. User Responsibilities</h2>
        <p className="legal-p">You agree to:</p>
        <ul className="legal-ul">
          <li>Provide accurate information when creating your account and entering portfolio data</li>
          <li>Keep your account credentials secure and not share them with others</li>
          <li>Use the platform only for lawful purposes</li>
          <li>Not attempt to reverse engineer, scrape, or exploit the platform</li>
          <li>Not upload or share content that violates any law or third-party rights</li>
          <li>Take full responsibility for all financial decisions made using BuyTune outputs</li>
        </ul>
        <p className="legal-p">You must be at least 18 years old to use BuyTune.</p>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">7. Limitation of Liability</h2>
        <p className="legal-p">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, BUYTUNE AND ITS OWNERS, OPERATORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR:</p>
        <ul className="legal-ul">
          <li>Any investment losses or financial damages arising from use of the platform</li>
          <li>Inaccuracies in AI-generated content, market data, or projections</li>
          <li>Loss of data, profits, or business opportunities</li>
          <li>Any indirect, incidental, consequential, or punitive damages</li>
          <li>Service interruptions, errors, or technical failures</li>
        </ul>
        <p className="legal-p">IN NO EVENT SHALL BUYTUNE'S TOTAL LIABILITY EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO BUYTUNE IN THE TWELVE MONTHS PRECEDING THE CLAIM, OR (B) $100 USD.</p>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">8. Indemnification</h2>
        <p className="legal-p">You agree to indemnify, defend, and hold harmless BuyTune and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable attorneys' fees) arising from: (a) your use of the platform; (b) your violation of these Terms; (c) your violation of any third-party right; or (d) any investment or financial decision you make based on platform outputs.</p>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">9. Dispute Resolution and Arbitration</h2>
        <p className="legal-p">Any dispute, claim, or controversy arising out of or relating to these Terms or the platform shall be resolved by binding individual arbitration, not in court. You waive your right to a jury trial and to participate in a class action lawsuit or class-wide arbitration.</p>
        <p className="legal-p">Arbitration shall be conducted under the rules of the American Arbitration Association (AAA). The arbitration shall take place in Austin, Texas, or remotely by mutual agreement.</p>
        <p className="legal-p">Notwithstanding the above, either party may seek injunctive or other equitable relief in a court of competent jurisdiction to prevent irreparable harm.</p>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">10. Account Termination</h2>
        <p className="legal-p">BuyTune reserves the right to suspend or terminate any account at any time, with or without notice, for any reason including violation of these Terms or behavior that harms other users or the platform.</p>
        <p className="legal-p">You may delete your account at any time from your account settings. Upon deletion, your data will be handled as described in our <a href="/legal/privacy" className="legal-link">Privacy Policy</a>.</p>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">11. Subscription and Billing</h2>
        <p className="legal-p">BuyTune currently offers free access to all features. If paid tiers are introduced, pricing, billing cycles, and feature access will be disclosed clearly before any charge is made.</p>
        <h3 className="legal-h3">Refund Policy</h3>
        <p className="legal-p">If and when paid plans are introduced, refund requests must be submitted within 14 days of a charge. Refunds are issued at BuyTune's discretion and will not be provided for partial use of a billing period. To request a refund, contact <strong>support@buytune.io</strong>.</p>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">12. Intellectual Property</h2>
        <p className="legal-p">All platform content, features, trademarks, and technology are the intellectual property of BuyTune. You may not reproduce, distribute, or create derivative works without written permission.</p>
        <p className="legal-p">You retain ownership of any portfolio data, financial information, or content you upload. By uploading content, you grant BuyTune a limited license to store and process it for the purpose of providing the service.</p>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">13. Third-Party Services</h2>
        <p className="legal-p">BuyTune integrates with third-party services including Finnhub (market data), Resend (email), Supabase (database), Vercel (hosting), Google Gemini, and xAI Grok (AI). Your use of the platform is also subject to the terms of these providers. BuyTune is not responsible for the accuracy, availability, or conduct of third-party services.</p>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">14. Disclaimers of Warranty</h2>
        <p className="legal-p">THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND. BUYTUNE EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ACCURACY OF MARKET DATA OR AI-GENERATED CONTENT.</p>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">15. Governing Law</h2>
        <p className="legal-p">These Terms are governed by and construed in accordance with the laws of the State of Texas, United States, without regard to conflict of law principles. Any legal proceedings not subject to arbitration shall be brought exclusively in the state or federal courts located in Austin, Texas.</p>
      </section>

      <section className="legal-section">
        <h2 className="legal-h2">16. Contact</h2>
        <p className="legal-p">Questions about these Terms? Contact us at <strong>legal@buytune.io</strong> or through the support section of the platform.</p>
      </section>
    </article>
  );
}
